spring.application.name=ustore
spring.datasource.url=jdbc:postgresql://localhost:5432/ustore
spring.datasource.username=postgres
spring.datasource.password=1097494590
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
jwt.secret=55a82bd0aaf566b07306def499a662819bb6043e48750f2c4d77b974127e967d
jwt.expiration=3600000