spring.application.name=ustore
spring.datasource.url=jdbc:postgresql://localhost:5432/ustore
spring.datasource.username=postgres
spring.datasource.password=1097494590
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
server.port=8081